"""Initial migration

Revision ID: 0260ced2c191
Revises: 
Create Date: 2025-09-27 23:33:34.666026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0260ced2c191'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('abonos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movimientos_caja', ['movimiento_id'], ['id'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('frecuencia')

    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movimientos_caja', ['movimiento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frecuencia', sa.VARCHAR(length=20), server_default=sa.text("'diario'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('abonos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
