"""Actualizar esquema según modelos

Revision ID: 268fa08cda82
Revises: 
Create Date: 2025-09-20 21:32:59.589217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268fa08cda82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('cancelado')

    # ### end Alembic commands ###
