"""Agregar columnas interes mensual a Cliente

Revision ID: 4c2f5d2031f9
Revises: f05e13926c34
Create Date: 2025-12-14 19:54:27.142798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2f5d2031f9'
down_revision = 'f05e13926c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_interes_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('proximo_interes_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('proximo_pago_fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('proximo_pago_fecha')
        batch_op.drop_column('proximo_interes_fecha')
        batch_op.drop_column('ultimo_interes_fecha')

    # ### end Alembic commands ###
