"""Agregar frecuencia a Cliente y ajustar Liquidacion

Revision ID: 680f46a50243
Revises: efad799a5cbf
Create Date: 2025-09-28 12:05:56.204317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680f46a50243'
down_revision = 'efad799a5cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_previo', sa.Float(), nullable=True))
        batch_op.create_unique_constraint(None, ['fecha'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('saldo_previo')

    # ### end Alembic commands ###
