"""Agregar campo frecuencia a Cliente

Revision ID: efad799a5cbf
Revises: 0260ced2c191
Create Date: 2025-09-28 11:50:23.430400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad799a5cbf'
down_revision = '0260ced2c191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frecuencia', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('frecuencia')

    # ### end Alembic commands ###
